# Generated by Django 5.0.1 on 2024-02-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_author_book_bookuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookUser',
        ),
    ]
