# Generated by Django 5.0.1 on 2024-02-23 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_remove_book_author_remove_bookuser_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('bio', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('genre', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.author')),
            ],
        ),
    ]
