# Generated by Django 5.0.1 on 2024-02-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='cheese',
            field=models.CharField(choices=[('mozzarella', 'Mozzarella'), ('vegan', 'Vegan'), ('low_fat', 'Low Fat')], default='mozzarella', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='crust_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('thin', 'Thin'), ('thick', 'Thick'), ('gluten_free', 'Gluten Free')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='sauce',
            field=models.CharField(choices=[('tomato', 'Tomato'), ('bbq', 'BBQ')], default='tomato', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='toppings',
            field=models.CharField(choices=[('pepperoni', 'Pepperoni'), ('chicken', 'Chicken'), ('ham', 'Ham'), ('pineapple', 'Pineapple'), ('peppers', 'Peppers'), ('mushrooms', 'Mushrooms'), ('onions', 'Onions')], default='pepperoni', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
