# Generated by Django 5.0.1 on 2024-02-23 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_pay_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pay',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='pay',
            name='cvc',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='pay',
            name='expiry_date',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='pay',
            name='name_on_card',
            field=models.CharField(default='', max_length=100),
        ),
    ]
