# Generated by Django 5.0.1 on 2024-02-23 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0007_pay_user_alter_pay_card_number_alter_pay_cvc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='user',
        ),
    ]
