# Generated by Django 5.0.1 on 2024-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0008_remove_pay_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pay',
            name='cvc',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pay',
            name='expiry_date',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='pay',
            name='name_on_card',
            field=models.CharField(max_length=100),
        ),
    ]
